#!/usr/bin/env python

import sys
from scraping import fetch_html, extract_wiki_links  # local module

def main():
    # 1. Read source page title from CLI argument, or default
    if len(sys.argv) < 2:
        title = 'potato'
    else:
        title = sys.argv[1]
    print(f"Fetching links from: {title}")

    # 2. Fetch HTML and extract links
    html = fetch_html(title)
    links = extract_wiki_links(html)

    # 3. Print results
    print(f"Found {len(links)} links.\n")
    for link in links:
        print(link)

if __name__ == "__main__":
    main()